name: govt-work-2019

channels:
  - conda-forge

dependencies:
  - python
  - beautifulsoup4
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - requests
  - selenium
  - sqlalchemy

  - pip:
    - pytrends
